import {afterEach, describe, expect, it, vi} from 'vitest';
import {LLMtrack, LLMtrackError} from './index.js';
afterEach(()=>vi.unstubAllGlobals());
const event={provider:'openai',model:'gpt-4o-mini',promptTokens:1,completionTokens:2};
describe('LLMtrack',()=>{
  it('sends the real ingest contract and accepts 200 duplicates',async()=>{const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({ok:true,duplicate:true})));vi.stubGlobal('fetch',fetch);const result=await new LLMtrack({apiKey:'x'}).trackSync({...event,idempotencyKey:'same'});expect(result?.duplicate).toBe(true);expect(fetch.mock.calls[0][0]).toBe('https://llm-track.com/api/ingest');expect(fetch.mock.calls[0][1].headers['Idempotency-Key']).toBe('same');expect(JSON.parse(fetch.mock.calls[0][1].body).prompt_tokens).toBe(1);});
  it('never throws from track and reports bad input',async()=>{const errors:LLMtrackError[]=[];new LLMtrack({apiKey:'x',onError:e=>errors.push(e)}).track({...event,provider:''});await vi.waitFor(()=>expect(errors[0].code).toBe('INVALID_PAYLOAD'));});
  it('rejects oversized metadata before fetch',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(new LLMtrack({apiKey:'x'}).trackSync({...event,metadata:{x:'a'.repeat(8193)}})).rejects.toMatchObject({code:'INVALID_PAYLOAD'});expect(fetch).not.toHaveBeenCalled();});
  it('does not retry a bad key',async()=>{const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({}),{status:401}));vi.stubGlobal('fetch',fetch);await expect(new LLMtrack({apiKey:'bad'}).trackSync(event)).rejects.toMatchObject({code:'INVALID_API_KEY'});expect(fetch).toHaveBeenCalledTimes(1);});
  it('keeps an automatic idempotency key stable across 5xx retries',async()=>{const fetch=vi.fn().mockResolvedValueOnce(new Response('{}',{status:500})).mockResolvedValueOnce(new Response(JSON.stringify({ok:true,duplicate:true})));vi.stubGlobal('fetch',fetch);await new LLMtrack({apiKey:'x',maxRetries:2}).trackSync(event);expect(fetch.mock.calls[0][1].headers['Idempotency-Key']).toBe(fetch.mock.calls[1][1].headers['Idempotency-Key']);});
  it('reads the real nested visibility context',async()=>{const warnings:any[]=[];const body={ok:true,duplicate:false,id:'1',cost:0,consumption_source:'included',dashboard_visible:false,visibility_reason:'free_source_mismatch',visibility_context:{mismatched_fields:['model'],key_binding:{provider:'openai',model:'bound',feature:'chat'},submitted:{provider:'openai',model:'other',feature:'chat'}},pricing_status:'unknown_model'};vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify(body))));const result=await new LLMtrack({apiKey:'x',onWarning:w=>warnings.push(w)}).trackSync(event);expect(result && 'visibilityContext' in result && result.visibilityContext?.mismatchedFields).toEqual(['model']);expect(warnings.map(w=>w.code)).toEqual(['NOT_DASHBOARD_VISIBLE','UNKNOWN_MODEL']);expect(warnings[0].message).toContain('model=bound');});
});
